### ISSUE TITLE
Support reading api key and member token from file

### ISSUE THREAD

**Issue by grodin** [brettweavnet/trello_cli#17]
The tool is great, but I keep my dotfiles in a public repo, and so I don't want to stick the `EXPORT` lines in my `.zshrc`. The workaround is to keep them in a separate file and source that at shell startup, but it would be much nicer if `trello_cli` could just read the necessary lines from a file.

I don't know python at all, or I'd happily submit a PR, but I thought it was worth raising the issue.

**Comment by brettweavnet** [comment]
@grodin closing this issue.  Please let me know if you are still having problems leveraging env variables.
