### ISSUE TITLE
failed to build native extension (json related?)

### ISSUE THREAD

**Issue by q785905925** [brettweavnet/trello_cli#20]
i am running rvm in ubuntu 14 with rubies 2.3.0 dev and 2.2.0. 
```
max@localhost ~> gem install trello_cli
Fetching: builder-3.2.2.gem (100%)
Successfully installed builder-3.2.2
Fetching: thread_safe-0.3.4.gem (100%)
Successfully installed thread_safe-0.3.4
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: json-1.8.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing trello_cli:
        ERROR: Failed to build gem native extension.

    /home/max/.rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20150122-11071-q8rqc4.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling generator.c
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function 'fbuffer_to_s':
../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [enabled by default]
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/max/.rvm/gems/ruby-2.2.0/gems/json-1.8.0 for inspection.
Results logged to /home/max/.rvm/gems/ruby-2.2.0/extensions/x86_64-linux/2.2.0/json-1.8.0/gem_make.out
```

I think the issue is with the json gem because i get the same error when installing that

```
max@localhost ~> gem install json -v 1.8.0
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    /home/max/.rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20150122-11230-1fay19p.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling generator.c
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function 'fbuffer_to_s':
../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [enabled by default]
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/max/.rvm/gems/ruby-2.2.0/gems/json-1.8.0 for inspection.
Results logged to /home/max/.rvm/gems/ruby-2.2.0/extensions/x86_64-linux/2.2.0/json-1.8.0/gem_make.out
```
no idea what is the probem here, but i am forking and trying with a different json version

**Comment by q785905925** [comment]
removing the json 1.8.0 dependency fixed it.

just changing

  `gem.add_runtime_dependency 'json', '1.8.0' # Added to resolve version conflict`

to

  `gem.add_runtime_dependency 'json'`

you can see my fork at https://github.com/q785905925/trello_cli/

i can submit a pull request if you like. feel free to close this issue as well

**Comment by brettweavnet** [comment]
@q785905925 does setting the version to 

```
gem.add_runtime_dependency 'json', '~> 1.8.2'
```

resolve the issue?

If so, please submit a PR with the above and I will gladly merge and release.

Thanks

**Comment by jonathanpa** [comment]
Yes there is no problem with ruby 2.1.0 (as specified in `.ruby-version`), but fails for me for ruby 2.2.0.

**Comment by brettweavnet** [comment]
@jonathanpa @q785905925 I’ve updated the gems and tested it with ruby 2.2.0.  I release 0.4.1 to ruby gems.  Can you reinstall and let me know if it works?  Thanks

**Comment by jonathanpa** [comment]
It works with ruby 2.2.0.

**Comment by brettweavnet** [comment]
thanks for confirming

**Comment by piga** [comment]
Hey, I have the same problem like Ghost. Where can I make this changes what you described. I was looking in Gemfile.lock but I can't find this line "gem.add_runtime_dependency 'json', '1.8.0' # Added to resolve version conflict". Thanks

**Comment by weavenet** [comment]
@piga changes are here. 

https://github.com/weavenet/trello_cli/commit/b440d8330e6784c5d1791ce15abf3cb0b83c7ae7#diff-5ace5506a8e78711b1913aaf6c2a1c37

 Let me know if you have any luck with it

**Comment by piga** [comment]
@weavenet thanks for response but I didn't try your suggestion bacause I never worked with trello_cli. I switched from rubie 2. 2. 2 to 2.0.0 and I didn't have problems with bunde install.
