### ISSUE TITLE
Config file with default settings

### ISSUE THREAD

**Issue by mbajur** [brettweavnet/trello_cli#22]
Hey!
I'm pretty excited about that tool but one thing is missing in my opinion - an option to create a config file with default settings. There are probably a lot of usecases for such file but the first one that comes to my mind (and the one which encouraged me to create that issue) is to set a board ID for a project i'm currently working (by setting it in `<app_root>/.trellocli` or anywhere else) so i could just use `trello list list -o tsv` and the default `-b` flag would be taken from that `.trellocli` config file. Also, it would be nice to set a default output formatter in there.

I would love to make a PR for that but i'm affraid it's a bit too complicated for me.

What do you guys think?

**Comment by brettweavnet** [comment]
@mbajur Thanks for the feedback!

What are your thoughts on using a wrapper script to provide the described functionality.  For example:

https://gist.github.com/brettweavnet/af002bde11adc8fb7b31

I would prefer to avoid adding the functionality to the core CLI to avoid cross platform compatibility issues.

Let me know your thoughts.

**Comment by mbajur** [comment]
Yes! Thats awesome :) thanks! I think you should somehow add it to the readme

Thanks! :beers:

**Comment by brettweavnet** [comment]
@mbajur updated https://github.com/brettweavnet/trello_cli/blob/master/README.md

Thanks and let me know if you have any other issues.
